/* Single-translation-unit entry point for environments that use tcc -run. */
#include "all.h"
#include "graph.c"
#include "hashtable.c"
#include "queue.c"
#include "bfs.c"
#include "heap.c"
#include "sort.c"
#include "stack.c"
#include "trie.c"
#include "unionfind.c"
#include "recommend.c"
#include "requests.c"
#include "persistence.c"
#include "json.c"
#include "stats.c"
#include "server.c"
#include "main.c"
